### ISSUE TITLE
Documentation mismatch for config_struct::create_enum_from_source

### ISSUE THREAD

**Issue by wyf18** [Mistodon/config_struct#10]
Hello! 🐙
While scanning crates.io. we noticed a document-code mismatch issue in this crate, we think the doc examples are generally meant to illustrate why someone would want to use the item.

# Location

documentation for config_struct::create_enum_from_source.
(https://docs.rs/config_struct/0.5.0/config_struct/fn.create_enum_from_source.html)

# Summary

The example of the document does not mention the `create_enum_from_source` function, it is not clear how to use it.

Thank you for checking out this issue! 👍🤗

**Comment by mistodon** [comment]
Hi there - this crate is now deprecated (and should have been a long time ago, my apologies).

It has been replaced by this project: https://github.com/mistodon/edres - feel free to open an issue there if it's still relevant.
