### ISSUE TITLE
A way to customize the struct's generated

### ISSUE THREAD

**Issue by sudo-ben** [Mistodon/config_struct#4]
json_typegen!("pub Point", "http://example.com/someapi/point.json", {
    use_default_for_missing_fields,
    "/foo/bar": {
        use_type: "map"
    }
});

Similar to how this tool does it
https://github.com/evestera/json_typegen/blob/master/README.md

**Comment by mistodon** [comment]
Hi there - this crate is now deprecated (and should have been a long time ago, my apologies).

It has been replaced by this project: https://github.com/mistodon/edres - feel free to open an issue there if it's still relevant.
