### ISSUE TITLE
Better handling of optional fields

### ISSUE THREAD

**Issue by mohansammeta** [Mistodon/config_struct#7]
Consider the below example : 

```
{
  "my_structs": [
    {
      "struct_with_a_and_b": {
        "a": 123
      }
    },
    {
      "struct_with_a_and_b": {
        "a": 111,
        "b": 123
      }
    }
  ]
}

```

Generated constant will have "b" value generated but it is not declared as field in "struct_with_a_and_b".

**Comment by mistodon** [comment]
Hi there - this crate is now deprecated (and should have been a long time ago, my apologies).

It has been replaced by this project: https://github.com/mistodon/edres - feel free to open an issue there if it's still relevant.
