### ISSUE TITLE
Values that change at build time?

### ISSUE THREAD

**Issue by rope-hmg** [Mistodon/config_struct#8]
In my current project I'm using this crate for my standard config, but I have two fields that I have to do something custom for. Their values are replaced with something else at build time. For example one of them is a time stamp. For this, I'm generating the time stamp in the build.rs and then just formatting some rust code string and writing it to a file.

It would be nice if there were some mechanism within this crate to add these kinds of fields. They don't change for the lifetime of the compiled application, but can't be known outside of build time. The kind of solution I'm looking for is something like a replacement map. Not sure how well that would play with the nested data formats though.

**Comment by mistodon** [comment]
Hi there - this crate is now deprecated (and should have been a long time ago, my apologies).

It has been replaced by this project: https://github.com/mistodon/edres - feel free to open an issue there if it's still relevant.
