### ISSUE TITLE
`config_struct` does not escape keywords

### ISSUE THREAD

**Issue by Starwort** [Mistodon/config_struct#9]
When compiling my project, I get invalid output; with errors such as

> ```
> error: expected identifier, found keyword `type`
> error: expected identifier, found keyword `move`
> ```

These errors would be fixed by `config_struct` escaping keywords in the output (`r#type`, `r#move`)

**Comment by mistodon** [comment]
Hi there - this crate is now deprecated (and should have been a long time ago, my apologies).

It has been replaced by this project: https://github.com/mistodon/edres - feel free to open an issue there if it's still relevant.
